Added in view all reviews view
omris-elda/fe-nc-games pull request #1
Opened 2022-09-26 14:33 UTC by omris-elda

2022-09-26 14:52 UTC, dappernerddesigns requested changes
There is very little contrast between your background colour and your text. This makes it incredibly hard to read and may cause eye strain.

This PR does not list all reviews in browser because you have not provided a link to them. You have rendered your review cards on the path of /reviews but not provided any navigation to that path.

When going to that path, the review cards should not be showing the body of the review. For a longer review that would mean a huge card! The ticket for this in BE would have stated that the body key was not in the list of what we were looking for. 

On a mobile screen your images are made so small that they may as well not be there. Consider how the card lays out on a mobile screen as that is most likely the device being used to view this application. 

Make the changes suggested and please resubmit this PR.

2022-09-26 14:52 UTC, dappernerddesigns commented on src/components/Reviews/Reviews.jsx
> +        console.log("inside of the reviews useeffect");
Make sure to remove console logs when you don't need them anymore

2022-09-27 10:05 UTC, omris-elda commented
The body is still in there, however now it will not exceed 150 characters, keeping the cards nice and short. Since the body is already in the back end, it seems a waste not to use it and the cards look bland and boring otherwise, with no inspiration to click on them.

2022-09-27 10:31 UTC, k-huggs reviewed
hi mate your queries shouldn't be in your components folder.
All good to merge!

2022-09-27 10:36 UTC, merged